### ISSUE TITLE
createThrottle not working with createEffect

### ISSUE THREAD

**Issue by yogurt1** [sergeysova/patronum#30]
Expected behavior:

`createThrottle()` applied to `createEffect()` returns event that forward params to fx

Reproducing:

https://share.effector.dev/y2n8dtJw

**Comment by sergeysova** [comment]
@yogurt1 Thank you for your contribution.

You should trigger `fx` to run throttled.

```ts
const throttled = createThrottle(source, timeout)

source() // after timeout throttled will run
```

https://share.effector.dev/UyjiKSTA

---

with `patronum@next` or `0.100.1` you can use `throttle({ source, timeout, target })` syntax:

```js
const source = createEvent()
throttle({source, timeout: 300, target: fx})

source(1)
source(2)
```

https://share.effector.dev/KC3MBolg

**Comment by sergeysova** [comment]
Closed due to inactivity
