### ISSUE TITLE
Add object arguments form for `combineEvents`

### ISSUE THREAD

**Issue by sergeysova** [sergeysova/patronum#33]
Should support config normalization

```ts
const event = combineEvents({
  events: { event1, event2, event3 }
});
```

**Comment by doasync** [comment]
How are you going to differentiate if the object (first param) is `source` or `config`?

**Comment by sergeysova** [comment]
I want to remove the support of the previous configuration.
Leave just one — object form `combineEvents({ events: {} })`

**Comment by doasync** [comment]
Seems reasonable for `combineEvents`, as there is a need for `reset` and `target` options
